/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/event-service/user-vendor/update/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateUserVendor"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-service/place/update/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updatePlace"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-service/event/update-event/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateEvent"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-service/user/upload-secondary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["uploadSecondaryImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-service/user/upload-avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["uploadAvatar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-service/user/subscriptions/{subscriptionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["subscribe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-service/user/select-lending-template/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["selectLendingTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-service/user/add-cache/{amount}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addCache"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-service/user-vendor/rate-user-vendor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rateUserVendor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-service/user-vendor/create-user-vendor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createUserVendor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-service/place/rate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rateUserVendor_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-service/place/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createPlace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-service/event/create-event": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-service/event/ai-review/{eventId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["getEvents"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-service/event-vendor/request/{eventVendorId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["requestEventService"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-service/event-vendor/rejecit/{eventVendorId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["confirmRejectService"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-service/event-vendor/confirm/{eventVendorId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["confirmEventService"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-service/user/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllSubscriptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-service/user/subscriptions-business": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllBusinessSubscriptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-service/user/get-current-user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-service/user-vendor/search-user-vendors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["searchUserVendors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-service/user-vendor/get-user-vendor/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUserVendorById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-service/user-vendor/get-user-vendor-by-user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUserVendorByUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-service/user-vendor/get-rating/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUserVendorRating"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-service/user-vendor/get-popular-vendors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUserVendor"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-service/place/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["searchUserVendors_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-service/place/get-rating/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUserVendorRating_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-service/place/get-popular-places": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEvents_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-service/place/get-place/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPlace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-service/place/get-place-by-user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPlaceByUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-service/event/get-event/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEvent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-service/event/get-all-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllEventsByUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-service/event-vendor/get-daily-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDailyInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-service/event-vendor/find-rejected-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findRejectedEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-service/event-vendor/find-confirmed-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findConfirmedEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-service/event-vendor/find-approval-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findApprovalEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-service/event-template/get-popular-event-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPopularEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-service/event-template/get-by-id/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-service/user-vendor/delete/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteUserVendor"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-service/place/delete/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deletePlace"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-service/event/delete-event/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteEvent"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UserVendorRequest: {
            title: string;
            description?: string;
            /** Format: float */
            experience?: number;
            /** Format: float */
            averageCost?: number;
            /** Format: binary */
            mainImage?: string;
            /** Format: binary */
            secondaryImage?: string;
            /** @enum {string} */
            serviceType: "PRESENTERS" | "SINGERS" | "DANCERS" | "GROUP" | "OPERATORS" | "PHOTOGRAPH" | "MOBILOGRAPH" | "TRANSPORT" | "DECORATORS" | "ANIMATORS" | "TECHNICAL_STAFF" | "SECURITY" | "SOUND_ENGINEERS" | "MEDICAL_WORKERS" | "STYLISTS" | "TECHNICAL_EQUIPMENT" | "HAIR_DRESSERS" | "CLOTHING_SUPPLIERS" | "FLOWER_SUPPLIERS";
        };
        UserVendorResponse: {
            /** Format: int64 */
            id: number;
            title: string;
            description?: string;
            /** Format: float */
            experience?: number;
            /** Format: float */
            averageCost?: number;
            serviceType: string;
            /** Format: float */
            rating?: number;
            isAIRecommended: boolean;
            mainImage?: string;
            secondaryImage?: string;
            airecommended?: boolean;
        };
        PlaceRequest: {
            title: string;
            /** @enum {string} */
            cityEnum?: "ALMATY" | "ASTANA" | "SHYMKENT" | "ATYRAU" | "KOKSHETAU";
            street?: string;
            description?: string;
            /** Format: float */
            cost?: number;
            /** Format: binary */
            mainImage?: string;
            /** Format: binary */
            secondaryImage?: string;
        };
        PlaceResponse: {
            /** Format: int64 */
            id: number;
            title: string;
            /** @enum {string} */
            cityEnum?: "ALMATY" | "ASTANA" | "SHYMKENT" | "ATYRAU" | "KOKSHETAU";
            street?: string;
            description?: string;
            mainImage?: string;
            secondaryImage?: string;
            /** Format: float */
            rating?: number;
            /** Format: float */
            cost?: number;
        };
        EventRequest: {
            title: string;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            endedAt?: string;
            description?: string;
            /** Format: int64 */
            placeId: number;
            eventServices: components["schemas"]["EventServiceRequest"][];
            emailList: string[];
        };
        EventServiceRequest: {
            /** Format: int64 */
            id: number;
        };
        EventResponse: {
            /** Format: int64 */
            id: number;
            title: string;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            endedAt?: string;
            /** Format: float */
            totalCost: number;
            description?: string;
            place?: components["schemas"]["PlaceResponse"];
            emailList: string[];
            eventServices: components["schemas"]["EventVendorResponse"][];
        };
        EventVendorResponse: {
            /** Format: int64 */
            id: number;
            title: string;
            description?: string;
            /** Format: float */
            experience?: number;
            /** Format: float */
            averageCost?: number;
            serviceType: string;
            /** Format: float */
            rating?: number;
            mainImage?: string;
            secondaryImage?: string;
            /** Format: int64 */
            eventVendorId: number;
            /** @enum {string} */
            status?: "CONFIRMED" | "PENDING" | "REJECTED";
        };
        ApiResponse: {
            /** @enum {string} */
            status: "SUCCESS" | "FAIL";
            message: string;
        };
        Event: {
            /** Format: int64 */
            id: number;
            title: string;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            endedAt?: string;
            description?: string;
            emailList?: string;
            place?: components["schemas"]["Place"];
            user?: components["schemas"]["User"];
            eventServices: components["schemas"]["EventVendor"][];
        };
        EventVendor: {
            /** Format: int64 */
            id: number;
            /** Format: float */
            cost: number;
            event: components["schemas"]["Event"];
            userVendor: components["schemas"]["UserVendor"];
            /** @enum {string} */
            status: "CONFIRMED" | "PENDING" | "REJECTED";
        };
        Place: {
            /** Format: int64 */
            id: number;
            title: string;
            /** @enum {string} */
            cityEnum?: "ALMATY" | "ASTANA" | "SHYMKENT" | "ATYRAU" | "KOKSHETAU";
            street?: string;
            description?: string;
            /** Format: float */
            cost?: number;
            mainImage?: string;
            secondaryImage?: string;
            events: components["schemas"]["Event"][];
            placeRatings: components["schemas"]["PlaceRating"][];
            user?: components["schemas"]["User"];
        };
        PlaceRating: {
            /** Format: int64 */
            id: number;
            /** Format: float */
            rating: number;
            comment?: string;
            user: components["schemas"]["User"];
            place: components["schemas"]["Place"];
        };
        Role: {
            /** Format: int64 */
            id?: number;
            /** @enum {string} */
            name?: "ROLE_USER" | "ROLE_BUSINESS";
        };
        SocialMedia: {
            url: string;
            /** @enum {string} */
            socialMediaType: "WHATS_UP" | "TELEGRAM" | "INSTAGRAM" | "OTHERS";
        };
        Subscription: {
            /** Format: int64 */
            id: number;
            /** @enum {string} */
            name: "STANDARD" | "STANDARD_PRO" | "PREMIUM_PRO" | "FREE";
            description?: string;
            /** Format: float */
            price: number;
            /** Format: float */
            priceUl: number;
            /** Format: int32 */
            durationDays: number;
            isBusiness: boolean;
        };
        User: {
            /** Format: int64 */
            id: number;
            username: string;
            email: string;
            password: string;
            /** Format: float */
            cache: number;
            /** @enum {string} */
            buzType?: "TOO" | "IP";
            avatarImage?: string;
            secondaryImage?: string;
            /** Format: int64 */
            preferedLendingTemplate?: number;
            placeRatings: components["schemas"]["PlaceRating"][];
            userVendorRatings: components["schemas"]["UserVendorRating"][];
            places: components["schemas"]["Place"][];
            userVendor: components["schemas"]["UserVendor"][];
            socialMedia: components["schemas"]["SocialMedia"][];
            userSubscriptions: components["schemas"]["UserSubscription"][];
            roles: components["schemas"]["Role"][];
        };
        UserSubscription: {
            /** Format: int64 */
            id: number;
            user: components["schemas"]["User"];
            subscription: components["schemas"]["Subscription"];
            /** Format: date-time */
            startDate: string;
            /** Format: date-time */
            endDate: string;
            isActive: boolean;
            active?: boolean;
        };
        UserVendor: {
            /** Format: int64 */
            id: number;
            title: string;
            description?: string;
            /** Format: float */
            experience?: number;
            /** Format: float */
            averageCost?: number;
            mainImage?: string;
            secondaryImage?: string;
            /** Format: int32 */
            priority?: number;
            isAIRecommended?: boolean;
            user?: components["schemas"]["User"];
            /** @enum {string} */
            serviceType: "PRESENTERS" | "SINGERS" | "DANCERS" | "GROUP" | "OPERATORS" | "PHOTOGRAPH" | "MOBILOGRAPH" | "TRANSPORT" | "DECORATORS" | "ANIMATORS" | "TECHNICAL_STAFF" | "SECURITY" | "SOUND_ENGINEERS" | "MEDICAL_WORKERS" | "STYLISTS" | "TECHNICAL_EQUIPMENT" | "HAIR_DRESSERS" | "CLOTHING_SUPPLIERS" | "FLOWER_SUPPLIERS";
            userVendorRating: components["schemas"]["UserVendorRating"][];
            airecommended?: boolean;
        };
        UserVendorRating: {
            /** Format: int64 */
            id: number;
            /** Format: float */
            rating: number;
            comment?: string;
            user: components["schemas"]["User"];
            userVendor: components["schemas"]["UserVendor"];
        };
        RateRequest: {
            /** Format: int64 */
            id: number;
            comment: string;
            /** Format: float */
            rating: number;
        };
        EventVendorByUser: {
            /** Format: float */
            cost: number;
        };
        SubscriptionResponse: {
            /** @enum {string} */
            subscription?: "STANDARD" | "STANDARD_PRO" | "PREMIUM_PRO" | "FREE";
        };
        UserResponse: {
            /** Format: int64 */
            id: number;
            username: string;
            email: string;
            socialMedia: components["schemas"]["SocialMedia"][];
            avatarImage?: string;
            secondaryImage?: string;
            /** Format: float */
            rating: number;
            /** Format: int32 */
            comment: number;
            /** Format: float */
            cache: number;
            /** Format: int64 */
            preferedTemplate: number;
            subscription: components["schemas"]["SubscriptionResponse"][];
        };
        PageableResponseUserVendorResponse: {
            /** Format: int32 */
            totalCount: number;
            /** Format: int32 */
            totalPages: number;
            list: components["schemas"]["UserVendorResponse"][];
        };
        PageableResponseRatingResponse: {
            /** Format: int32 */
            totalCount: number;
            /** Format: int32 */
            totalPages: number;
            list: components["schemas"]["RatingResponse"][];
        };
        RatingResponse: {
            /** Format: int64 */
            id: number;
            /** Format: float */
            rating: number;
            comment: string;
            user: components["schemas"]["UserDetails"];
        };
        UserDetails: {
            /** Format: int64 */
            id: number;
            username: string;
            avatarUrl?: string;
        };
        PageableResponsePlaceResponse: {
            /** Format: int32 */
            totalCount: number;
            /** Format: int32 */
            totalPages: number;
            list: components["schemas"]["PlaceResponse"][];
        };
        PageableResponseEventResponse: {
            /** Format: int32 */
            totalCount: number;
            /** Format: int32 */
            totalPages: number;
            list: components["schemas"]["EventResponse"][];
        };
        DailyEventSummaryDto: {
            /** Format: date */
            date: string;
            /** Format: int64 */
            pendingCount: number;
            /** Format: int64 */
            confirmedCount: number;
            /** Format: int64 */
            rejectedCount: number;
            /** Format: double */
            sumCost: number;
        };
        FullEventVendorResponse: {
            /** Format: int64 */
            id: number;
            /** Format: float */
            cost: number;
            event: components["schemas"]["EventResponse"];
            userVendor: components["schemas"]["UserVendorResponse"];
        };
        PageableResponseFullEventVendorResponse: {
            /** Format: int32 */
            totalCount: number;
            /** Format: int32 */
            totalPages: number;
            list: components["schemas"]["FullEventVendorResponse"][];
        };
        EventTemplateResponse: {
            /** Format: int64 */
            id: number;
            title: string;
            description?: string;
            mainImage?: string;
            location?: string;
            /** Format: double */
            rating?: number;
        };
        EventTemplateResponseList: {
            eventTemplates: components["schemas"]["EventTemplateResponse"][];
        };
        EventTemplateRatingResponse: {
            /** Format: int64 */
            id: number;
            /** Format: double */
            rating: number;
            comment: string;
            type: string;
            user: components["schemas"]["UserDetails"];
            /** Format: date */
            date: string;
        };
        FullEventTemplateResponse: {
            /** Format: int64 */
            id: number;
            title: string;
            description?: string;
            mainImage?: string;
            secondaryImage?: string;
            phoneNumber?: string;
            /** Format: double */
            rating?: number;
            socialMedia: components["schemas"]["SocialMediaEventTemplate"][];
            services: components["schemas"]["UserVendorTemplateResponse"][];
            ratings: components["schemas"]["EventTemplateRatingResponse"][];
        };
        SocialMediaEventTemplate: {
            url: string;
            /** @enum {string} */
            socialMediaType: "WHATS_UP" | "TELEGRAM" | "INSTAGRAM" | "OTHERS";
        };
        UserVendorTemplateResponse: {
            /** Format: int64 */
            id: number;
            title?: string;
            additionalVendors?: string;
            /** Format: float */
            rating?: number;
            /** Format: float */
            reviews?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    updateUserVendor: {
        parameters: {
            query: {
                request: components["schemas"]["UserVendorRequest"];
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserVendorResponse"];
                };
            };
        };
    };
    updatePlace: {
        parameters: {
            query: {
                placeRequest: components["schemas"]["PlaceRequest"];
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PlaceResponse"];
                };
            };
        };
    };
    updateEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EventResponse"];
                };
            };
        };
    };
    uploadSecondaryImage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    uploadAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    subscribe: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subscriptionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserSubscription"];
                };
            };
        };
    };
    selectLendingTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    addCache: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                amount: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rateUserVendor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    createUserVendor: {
        parameters: {
            query: {
                request: components["schemas"]["UserVendorRequest"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserVendorResponse"];
                };
            };
        };
    };
    rateUserVendor_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    createPlace: {
        parameters: {
            query: {
                placeRequest: components["schemas"]["PlaceRequest"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PlaceResponse"];
                };
            };
        };
    };
    createEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EventResponse"];
                };
            };
        };
    };
    getEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    requestEventService: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventVendorId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventVendorByUser"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    confirmRejectService: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventVendorId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    confirmEventService: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventVendorId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    getAllSubscriptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Subscription"][];
                };
            };
        };
    };
    getAllBusinessSubscriptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Subscription"][];
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    searchUserVendors: {
        parameters: {
            query?: {
                q?: string;
                minExperience?: number;
                maxExperience?: number;
                serviceType?: "PRESENTERS" | "SINGERS" | "DANCERS" | "GROUP" | "OPERATORS" | "PHOTOGRAPH" | "MOBILOGRAPH" | "TRANSPORT" | "DECORATORS" | "ANIMATORS" | "TECHNICAL_STAFF" | "SECURITY" | "SOUND_ENGINEERS" | "MEDICAL_WORKERS" | "STYLISTS" | "TECHNICAL_EQUIPMENT" | "HAIR_DRESSERS" | "CLOTHING_SUPPLIERS" | "FLOWER_SUPPLIERS";
                minCost?: number;
                maxCost?: number;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageableResponseUserVendorResponse"];
                };
            };
        };
    };
    getUserVendorById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserVendorResponse"];
                };
            };
        };
    };
    getUserVendorByUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserVendorResponse"][];
                };
            };
        };
    };
    getUserVendorRating: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageableResponseRatingResponse"];
                };
            };
        };
    };
    getUserVendor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserVendorResponse"][];
                };
            };
        };
    };
    searchUserVendors_1: {
        parameters: {
            query?: {
                q?: string;
                cityEnum?: "ALMATY" | "ASTANA" | "SHYMKENT" | "ATYRAU" | "KOKSHETAU";
                street?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageableResponsePlaceResponse"];
                };
            };
        };
    };
    getUserVendorRating_1: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageableResponseRatingResponse"];
                };
            };
        };
    };
    getEvents_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PlaceResponse"][];
                };
            };
        };
    };
    getPlace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PlaceResponse"];
                };
            };
        };
    };
    getPlaceByUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PlaceResponse"][];
                };
            };
        };
    };
    getEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EventResponse"];
                };
            };
        };
    };
    getAllEventsByUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageableResponseEventResponse"];
                };
            };
        };
    };
    getDailyInfo: {
        parameters: {
            query: {
                startTime: string;
                endTime: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DailyEventSummaryDto"][];
                };
            };
        };
    };
    findRejectedEvents: {
        parameters: {
            query: {
                page: number;
                size: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageableResponseFullEventVendorResponse"];
                };
            };
        };
    };
    findConfirmedEvents: {
        parameters: {
            query: {
                page: number;
                size: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageableResponseFullEventVendorResponse"];
                };
            };
        };
    };
    findApprovalEvents: {
        parameters: {
            query: {
                page: number;
                size: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageableResponseFullEventVendorResponse"];
                };
            };
        };
    };
    getPopularEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EventTemplateResponseList"];
                };
            };
        };
    };
    getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FullEventTemplateResponse"];
                };
            };
        };
    };
    deleteUserVendor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    deletePlace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    deleteEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
}
